/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Content: typeof import('./src/components/user/content.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIn: typeof import('element-plus/es')['ElIn']
    ElInput: typeof import('element-plus/es')['ElInput']
    Homeleft: typeof import('./src/components/Homecomp/Homeleft.vue')['default']
    HomeleftComp: typeof import('./src/components/HomeleftComp.vue')['default']
    Homeright: typeof import('./src/components/Homecomp/Homeright.vue')['default']
    Nav: typeof import('./src/components/Homecomp/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Side: typeof import('./src/components/user/side.vue')['default']
    Text: typeof import('./src/components/Homecomp/text.vue')['default']
    Tick: typeof import('./src/components/Homecomp/tick.vue')['default']
  }
}
